// defaultProducts.js
export const defaultProducts = [
  {
    id: '1',
    name: 'Douce Robe Bébé Rose',
    price: 17990,
    image: 'https://images.unsplash.com/photo-1653835785932-1710eac6385d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiYWJ5JTIwZ2lybCUyMGRTCqpJfyxBS4J3p2b5e5EKju1cc1FjKiMh&ixlib=rb-4.1.0&q=80&w=1080',
    ageRange: '0-3 ans',
    category: 'Robes',
    description: 'Robe en coton doux parfaite pour les bébés, confortable et adorable',
    sizes: ['0-6m', '6-12m', '12-18m'],
    inStock: true,
    occasion: 'Décontracté',
  },
  {
    id: '2',
    name: 'Délice Floral d\'Été',
    price: 20990,
    image: 'https://images.unsplash.com/photo-1606761684249-01d88ca3c772?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0b2RkbGVyJTIwZ2lybCUyMGRTCqpJfyxBS4J3p2b5e5EKju1cc1FjKiMh&ixlib=rb-4.1.0&q=80&w=1080',
    ageRange: '3-7 ans',
    category: 'Robes',
    description: 'Robe légère à fleurs parfaite pour les journées d\'été et les jeux en plein air',
    sizes: ['3T', '4T', '5T', '6'],
    inStock: true,
    occasion: 'Décontracté',
  },
  {
    id: '3',
    name: 'Robe de Fête Élégante',
    price: 29990,
    image: 'https://images.unsplash.com/photo-1545871084-74033c05b595?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxraWRzJTIwcGFydHklMjBkcmVzc3xlbnwxfHx8fDE3Njc4MjM5MzB8MA&ixlib=rb-4.1.0&q=80&w=1080',
    ageRange: '7-12 ans',
    category: 'Robes',
    description: 'Belle robe de fête avec paillettes et tulle, parfaite pour les occasions spéciales',
    sizes: ['7', '8', '10', '12'],
    inStock: true,
    occasion: 'Fête',
  },
  {
    id: '4',
    name: 'Robe Mode Chic',
    price: 26990,
    image: 'https://images.unsplash.com/photo-1759313560250-3bb4bc1d10bc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjaGlsZHJlbiUyMGZhc2hpb24lMjBkcmVzc3xlbnwxfHx8fDE3Njc4MjM5MzF8MA&ixlib=rb-4.1.0&q=80&w=1080',
    ageRange: '12-15 ans',
    category: 'Robes',
    description: 'Robe tendance et élégante pour ados, parfaite pour les événements scolaires',
    sizes: ['S', 'M', 'L'],
    inStock: true,
    occasion: 'École',
  },
  {
    id: '5',
    name: 'Robe Soleil Jaune',
    price: 19790,
    image: 'https://images.unsplash.com/photo-1495543950194-0d30125ba897?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxnaXJsJTIwc3VtbWVyJTIwZHJlc3N8ZW58MXx8fHwxNzY3ODIzOTMxfDA&ixlib=rb-4.1.0&q=80&w=1080',
    ageRange: '3-7 ans',
    category: 'Robes',
    description: 'Robe d\'été lumineuse et joyeuse, respirante et confortable',
    sizes: ['3T', '4T', '5T'],
    inStock: true,
    occasion: 'Décontracté',
  },
  {
    id: '6',
    name: 'Robe de Princesse Rêvée',
    price: 32990,
    image: 'https://images.unsplash.com/photo-1653835785932-1710eac6385d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcmluY2VzcyUQBNOrnQlzo3ftqm0Jj5Sf9zEHlPApapd-rWsAHREzkweiTw&ixlib=rb-4.1.0&q=80&w=1080',
    ageRange: '7-12 ans',
    category: 'Robes',
    description: 'Faites de chaque petite fille une princesse avec cette robe magique',
    sizes: ['7', '8', '10', '12'],
    inStock: true,
    occasion: 'Fête',
  },
  {
    id: '7',
    name: 'Robe d\'Hiver Confortable',
    price: 25790,
    image: 'https://images.unsplash.com/photo-1606761684249-01d88ca3c772?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0b2RkbGVyJTIwZ2lybCUyMGRTCqpJfyxBS4J3p2b5e5EKju1cc1FjKiMh&ixlib=rb-4.1.0&q=80&w=1080',
    ageRange: '3-7 ans',
    category: 'Robes',
    description: 'Robe chaude et élégante pour temps froid, avec manches longues',
    sizes: ['3T', '4T', '5T', '6'],
    inStock: true,
    occasion: 'École',
  },
  {
    id: '8',
    name: 'Ado Décontracté Chic',
    price: 23390,
    image: 'https://images.unsplash.com/photo-1759313560250-3bb4bc1d10bc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjaGlsZHJlbiUyMGZhc2hpb24lMjBkcmVzc3xlbnwxfHx8fDE3Njc4MjM5MzF8MA&ixlib=rb-4.1.0&q=80&w=1080',
    ageRange: '12-15 ans',
    category: 'Robes',
    description: 'Robe décontractée moderne pour tous les jours, confortable et tendance',
    sizes: ['S', 'M', 'L'],
    inStock: false,
    occasion: 'Décontracté',
  },
  // … ajoute les autres produits par défaut ici
];